# Call this workflow to build Example in windows
name: Build example in windows

on:
  workflow_call:
    inputs:
      PLUGIN_SCOPE:
        required: true
        type: string
      PLUGIN_EXAMPLE_SCOPE:
        required: true
        type: string

jobs:
  build_example:
    env:
      PLUGIN_SCOPE: ${{ inputs.PLUGIN_SCOPE }}
      PLUGIN_EXAMPLE_SCOPE: ${{ inputs.PLUGIN_EXAMPLE_SCOPE }}
    runs-on: windows-latest
    timeout-minutes: 30
    defaults:
      run:
        shell: bash
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
      - name: "Build Example"
        run: ./.github/workflows/scripts/build-examples.sh windows ./lib/main.dart